### ISSUE TITLE
Double end message when use the /vda stop

### ISSUE THREAD

**Issue by EnderBoyHUN** [Plajer-Lair/Village_Defense#10]
**Describe the bug**
Double end message when use the ```/vda stop```.

**Steps to reproduce**
1. Use the ```/vda stop``` command
2. See error

**Environment:**
 - Server version: 1.12.2 with BungeeCord
 - Plugin version: 3.8.1
 - Plugins list: HD and WorldEdit

**Attachment**
![2018-07-12_20 37 55](https://user-images.githubusercontent.com/12803062/42652908-20dcbcc6-8614-11e8-9846-6c0c738f63ae.png)

**Comment by montlikadani** [comment]
Try restarting the server completely. This also comes to me, but this is a Java problem.

**Comment by EnderBoyHUN** [comment]
The restart not working.
On video:
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/pjOioxlGnOY/0.jpg)](http://www.youtube.com/watch?v=pjOioxlGnOY)

Maybe the BungeeCord wrong?

**Comment by EnderBoyHUN** [comment]
I looked without BungeeCord and same.

**Comment by Plajer** [comment]
Had similar issue while adding stop command to BuildBattle. I'll check it later.

**Comment by montlikadani** [comment]
Spread the bug :(
I checked your code, but I did not find a similar message anywhere.
