### ISSUE TITLE
The player in 45°

### ISSUE THREAD

**Issue by EnderBoyHUN** [Plajer-Lair/Village_Defense#11]
**Describe the bug**
If select the Hardcore or Premium Hardcore Master kit (this <20HP (10 heart)), then the player die at game start. After the player is in 45° (in outer view).

**Steps to reproduce**
1. Join a arena
2. Choose the Hardcover or Premium Hardcore Master kit
3. Wait the game start or use ```/vda forcestart```
4. Click respawn 
5. Swich outer view (default: F5)
6. See error

**Environment:**
 - Server version: [e.g. 1.12.2]
 - Plugin version: [e.g. 3.8.1]
 - Plugins list: HD and WorldEdit

**Attachment**
![2018-07-12_20 52 00](https://user-images.githubusercontent.com/12803062/42654364-a45e32ce-8618-11e8-952c-05a52af7ec64.png)
![2018-07-12_20 52 11](https://user-images.githubusercontent.com/12803062/42654414-d43c0b24-8618-11e8-98cb-c5c8197c78f0.png)
![2018-07-12_20 52 19](https://user-images.githubusercontent.com/12803062/42654415-d4565bf0-8618-11e8-9199-49f4589b4dcb.png)

**Comment by Plajer** [comment]
This is Minecraft bug and won't be fixed.
