### ISSUE TITLE
Teleportation bug on server join after /vd leave before leaving the server.

### ISSUE THREAD

**Issue by TomTheCreator** [Plajer-Lair/Village_Defense#12]
**Describe the bug**
You get teleported to the end location of the game if you join the server after using /vd leave command before you left the server.

**Steps to reproduce**
1. Join a game via sign
2. Type /vd leave
3. Leave the server via the Quit button.
4. Rejoin the server
5. BUG: You'll get teleported to the end location of the game.

NO ERROR

**Environment:**
 - Server version: 1.12.2
 - Plugin version: 3.9.1
 - Plugins list: AdvancedMobArena, ArmorStandTools, ASkyBlock, BanManager, BannerMaker, BlockBall, BungeePortals, BungeeTabListPlus, CheckNameHistory, ColorCube, CommandSpy, CoreProtect, DiscordSRV, Essentials, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, GrapplingHooksPlus, HeadsInventory, HeadsPlugin, HeavySpleef, HolographicDisplays, IPWhitelist, ItemFixer, KitBattle, LuckPerms, MassiveBooks, MassiveCore, MBedwars, MGConquer, MGFlyingCars, MGHorseRacingPlus, MGMobEscape, MGNoteblockBlitz, Minigames, Minigames-Regions, MinigamesLib, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, Murder, MyCommand, Paintball, Parkour, PlaceholderAPI, PlotSquared, Porty-Bukkit, PremiumVanish, ProtocolLib, Skript, SkyWarsReloaded, TreysDoubleJump, Vault, VentureChat, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, VoidGenerator, WorldEdit, WorldGuard

**Additional context**
For more information, contact Paintsplatters on Discord. Just helping him out. I checked it on his server and it was indeed happening. Anyway, I'm not updated with the current code changes so I thought I'd help him by creating this issue on Github.

**Comment by Plajer** [comment]
Set spawn priority of your spawn plugin to highest.
